config/urls.py
from django.contrib import admin
from django.urls import path, include
from pybo.views import base_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('common/', include('common.urls')),
    path('', base_views.index, name='index')
]

pybo/urls.py
from django.urls import path

from .views import base_views, question_views, answer_views, vote_views, comment_views

app_name = 'pybo'
# url 별칭 -> 네임 스페이스

urlpatterns = [
    # base_views.py
    # 인덱스 메인
    path('', base_views.index, name='index'),
    # 질문/답변 게시판
    path('board/', base_views.board, name='board'),
    # 나의 프로필
    path('profile/', base_views.profile, name='profile'),
    # 상세 페이지
    path('<int:question_id>/', base_views.detail, name='detail'),

    # question_views.py
    # 질문 등록
    path('question/create/', question_views.question_create,
         name='question_create'),
    # 질문 수정
    path('question/modify/<int:question_id>/', question_views.question_modify,
         name='question_modify'),
    # 질문 삭제
    path('question/delete/<int:question_id>/', question_views.question_delete,
         name='question_delete'),

    # answer_views.py
    # 답변 등록
    path('answer/create/<int:question_id>/', answer_views.answer_create,
         name='answer_create'),
    # 답변 수정
    path('answer/modify/<int:answer_id>/', answer_views.answer_modify,
         name='answer_modify'),
    # 답변 삭제
    path('answer/delete/<int:answer_id>/', answer_views.answer_delete,
         name='answer_delete'),

    # vote_views.py
    # 질문 추천
    path('vote/question/<int:question_id>/', vote_views.vote_question,
         name='vote_question'),
    # 답변 추천
    path('vote/answer/<int:answer_id>', vote_views.vote_answer,
         name='vote_answer'),

    # comment_views.py
    # 질문 댓글 등록
    path('comment/create/question/<int:question_id>', comment_views.comment_create_question,
         name='comment_create_question'),
    # 질문 댓글 수정
    path('comment/modify/question/<int:comment_id>', comment_views.comment_modify_question,
         name='comment_modify_question'),
    # 질문 댓글 삭제
    path('comment/delete/question/<int:comment_id>', comment_views.comment_delete_question,
         name='comment_delete_question'),
    # 답변 댓글 등록
    path('comment/create/answer/<int:answer_id>/', comment_views.comment_create_answer,
         name='comment_create_answer'),
    # 답변 댓글 수정
    path('comment/modify/answer/<int:comment_id>/', comment_views.comment_modify_answer,
         name='comment_modify_answer'),
    # 답변 댓글 삭제
    path('comment/delete/answer/<int:comment_id>/', comment_views.comment_delete_answer,
         name='comment_delete_answer'),

]

pybo/models.py
from django.db import models
from django.contrib.auth.models import User

# 질문 모델(테이블)
class Question(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               related_name='author_question')
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(User, related_name='voter_question')

    def __str__(self):
        return self.subject

# 답변 모델(테이블)
class Answer(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_answer')
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    # 외래키 제약조건 무시하고 연쇄 삭제 됨
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(User, related_name='voter_answer')

    def __str__(self):
        return self.content

# 댓글 모델
class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    question = models.ForeignKey(Question, null=True, blank=True,
                        on_delete=models.CASCADE)
    answer = models.ForeignKey(Answer, null=True, blank=True,
                        on_delete=models.CASCADE)

pybo/forms.py
from .models import Question, Answer, Comment
from django import forms

class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question   # 폼 클래스의 객체
        fields = ['subject', 'content']
        labels = { # 레이블을 한글로 변경
            'subject' : '제목',
            'content' : '내용'
        }

class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']
        labels ={
            'content': '답변내용'
        }

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']
        labels = {
            'content': '댓글내용'
        }

pybo/views/answer_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render
from django.utils import timezone

from pybo.forms import AnswerForm
from pybo.models import Question, Answer


@login_required(login_url='common:login')  #'@'을 데코레이터라 함
def answer_create(request, question_id):
    # 답변 등록
    question = get_object_or_404(Question, pk=question_id)
    if request.method == 'POST':
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user  #인증된 사용자(글쓴이)
            answer.question = question
            answer.create_date = timezone.now()
            answer.save()
            return redirect('pybo:detail', question_id=question.id)
    else:
        form = AnswerForm()
    context = {'question':question, 'form': form}
    return render(request, 'pybo/question_detail.html', context)

@login_required(login_url='common:login')
def answer_modify(request, answer_id):
    #답변 수정
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, "수정 권한이 없습니다.")
        return redirect('pybo:detail', question_id=answer.question.id)

    if request.method == "POST":
        form = AnswerForm(request.POST, instance=answer)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user
            answer.modify_date = timezone.now()
            answer.save()
            return redirect('pybo:detail', question_id=answer.question.id)
    else:
        form = AnswerForm(instance=answer)
    context = {'form': form}
    return render(request, 'pybo/answer_form.html', context)

@login_required(login_url='common:login')
def answer_delete(request, answer_id):
    # 답변 삭제
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '삭제 권한이 없습니다.')
        return redirect('pybo:detail', question_id=answer.id)
    else:
        answer.delete()
    return redirect('pybo:detail', question_id=answer.question.id)

pybo/views/base_views.py
from django.core.paginator import Paginator
from django.db.models import Count, Q
from django.shortcuts import render, get_object_or_404

from pybo.models import Question


def index(request):
    return render(request, 'pybo/index.html')

def profile(request):
    return render(request, 'pybo/profile.html')

def board(request):
    # 질문 목록
    # 127.0.0.1:8000/pybo/board/?page=1
    page = request.GET.get('page', '1')  # 페이지
    kw = request.GET.get('kw', '')       # 검색어
    so = request.GET.get('so', 'recent') # 정렬 기준

    # 정렬
    if so == 'recommend':
        question_list = Question.objects.annotate( #num_voter : 임시 필드
            num_voter=Count('voter')).order_by('-num_voter', '-create_date')
    elif so == 'popular':
        question_list = Question.objects.annotate( #num_answer : 임시 필드
            num_answer=Count('answer')).order_by('-num_answer', '-create_date')
    else:  # recent
        question_list = Question.objects.order_by('-create_date')

    if kw:
        question_list = question_list.filter(
            Q(subject__icontains=kw) |           # 제목 검색
            Q(content__icontains=kw) |           # 내용 검색
            Q(author__username__icontains=kw) |  # 질문 글쓴이
            Q(answer__author__username__icontains=kw) |#답변 글쓴이
            Q(answer__content__icontains=kw)
        ).distinct()    # 중복제거

    # 페이징 처리 -페이지당 10개씩 보여줌
    paginator = Paginator(question_list, 10)
    page_obj = paginator.get_page(page)

    context = {'question_list': page_obj, 'page': page, 'kw': kw, 'so':so}
    return render(request, 'pybo/question_list.html' ,context)

def detail(request, question_id):
    #question = Question.objects.get(id=question_id)
    question = get_object_or_404(Question, pk=question_id)
    context ={'question' : question}
    return render(request, 'pybo/question_detail.html', context)

pybo/views/comment_views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render
from django.utils import timezone

from pybo.forms import CommentForm
from pybo.models import Comment, Question, Answer


@login_required(login_url='common:login')
def comment_create_question(request, question_id):
    # 질문 댓글 등록
    question = get_object_or_404(Question, pk=question_id)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user       # 댓글 글쓴이 = 로그인된 회원
            comment.create_date = timezone.now()  # 작성일
            comment.question = question           # 댓글
            comment.save()
            return redirect('pybo:detail', question_id=question.id)
    else:
        form = CommentForm()
    context = {'form': form}
    return render(request, 'pybo/comment_form.html', context)

@login_required(login_url='common:login')
def comment_modify_question(request, comment_id):
    # 질문 댓글 수정
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.method == "POST":
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.modify_date = timezone.now()
            comment.save()
            return redirect("pybo:detail", question_id=comment.question.id)
    else:
        form = CommentForm(instance=comment)
    context = {'form': form}
    return render(request, 'pybo/comment_form.html', context)

@login_required(login_url='common:login')
def comment_delete_question(request, comment_id):
    # 질문 댓글 삭제
    comment = get_object_or_404(Comment, pk=comment_id)
    comment.delete()
    return redirect('pybo:detail', question_id=comment.question.id)

@login_required(login_url='common:login')
def comment_create_answer(request, answer_id):
    # 답변 댓글 등록
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.create_date = timezone.now()
            comment.answer = answer
            comment.save()
            return redirect('pybo:detail', question_id=answer.question.id)
    else:
        form = CommentForm()
    context = {'form': form}
    return render(request, 'pybo/comment_form.html', context)

@login_required(login_url='common:login')
def comment_modify_answer(request, comment_id):
    # 답변 댓글 수정
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.method == "POST":
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.modify_date = timezone.now()
            comment.save()
            return redirect('pybo:detail', question_id=comment.answer.question.id)
    else:
        form = CommentForm(instance=comment)
    context = {'form': form}
    return render(request, 'pybo/comment_form.html', context)

@login_required(login_url='common:login')
def comment_delete_answer(request, comment_id):
    # 답변 댓글 삭제
    comment = get_object_or_404(Comment, pk=comment_id)
    comment.delete()
    return redirect('pybo:detail', question_id=comment.answer.question.id)

pybo/views/question_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render, get_object_or_404
from django.utils import timezone

from pybo.forms import QuestionForm
from pybo.models import Question


@login_required(login_url='common:login')
def question_create(request):
    # 질문 등록
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.author = request.user  #인증된 사용자(글쓴이)
            question.create_date = timezone.now()
            question.save()
            return redirect('pybo:board')
    else:    # request.method == 'GET'
        form = QuestionForm()

    context = {'form': form}
    return render(request, 'pybo/question_form.html', context)

@login_required(login_url="common:login")
def question_modify(request, question_id):
    # 질문 수정
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request, "수정 권한이 없습니다.")
        return redirect('pybo:detail', question_id=question.id)

    if request.method == "POST":
        form = QuestionForm(request.POST, instance=question)
        if form.is_valid():
            question = form.save(commit=False)
            question.author = request.user
            question.modify_date = timezone.now()
            question.save()
            return redirect('pybo:detail', question_id=question.id)
    else:
        form = QuestionForm(instance=question)
    context = {'form': form}
    return render(request, 'pybo/question_form.html', context)

@login_required(login_url='common:login')
def question_delete(request, question_id):
    # 질문 삭제
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request, "삭제 권한이 없습니다.")
        return redirect('pybo:detail', question_id=question.id)
    else:
        question.delete()
    return redirect('pybo:board')

pybo/views/vote_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect

from pybo.models import Question, Answer


@login_required(login_url='common:login')
def vote_question(request, question_id):
    # 질문 추천
    question = get_object_or_404(Question, pk=question_id)
    if request.user == question.author:  #로그인한 사람 == 질문 글쓴이
        messages.error(request, '본인이 작성한 글은 추천할 수 없습니다.')
    else:
        question.voter.add(request.user)
    return redirect('pybo:detail', question_id=question.id)

@login_required(login_url='common:login')
def vote_answer(request, answer_id):
    # 답변 추천
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user == answer.author:
        messages.error(request, '본인이 작성한 글은 추천할 수 없습니다.')
    else:
        answer.voter.add(request.user)
    return redirect('pybo:detail', question_id=answer.question.id)

templates/pybo/answer_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
  <form method="post" class="post-form">
    {% csrf_token %}
    {% include "form_errors.html" %}
    <div class="form-group">
      <label for="content">답변내용</label>
      <textarea class="form-control" name="content" id="content"
                rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
    </div>
    <button type="submit" class="btn btn-primary">저장하기</button>
  </form>
</div>

{% endblock %}

templates/pybo/comment_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
  <h5 class="border-bottom pb-2">댓글 등록하기</h5>
  <form method="post" class="post-form my-3">
    {% csrf_token %}
    {% include 'form_errors.html' %}
    <div class="form-group">
      <label for="content">댓글 내용</label>
      <textarea class="form-control" name="content" id="content"
                rows="3">{{ form.content.value|default_if_none:'' }}</textarea>
    </div>
    <button type="submit" class="btn btn-primary">저장하기</button>
  </form>
</div>
{% endblock%}

templates/pybo/index.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'pybo/bootstrap.css' %}">
    <script src="{% static 'pybo/watch.js' %}"></script>
    <title>Welcome! PyWeb</title>
</head>
<body>
  {% include 'navbar.html' %}
  <div class="jumbotron">
    <div class="text-center">
      <h1>Welcome! Hava a Good Day!</h1>
    </div>
  </div>
  <div class="container">
      <div class="text-center">
          <img src="{% static 'pybo/friends.PNG' %}" alt="인공지능 스피커">
          <p id="demo" class="my-3"></p>
      </div>
  </div>

<script src="{% static 'pybo/jquery-3.6.0.js' %}"></script>
<script src="{% static 'pybo/bootstrap.js' %}"></script>
</body>
</html>

templates/pybo/question_detail.html
{% extends 'base.html' %}  <!--템플릿 상속-->
{% block content %}
<div class="container my-3">
  <!-- 사용자 오류 표시 -->
  {% if messages %}
  <div class="alert alert-danger my-3" role="alert">
    {% for message in messages %}
      <strong>{{ message.tags }}</strong>
      <ul><li>{{ message.message }}</li></ul>
    {% endfor %}
  </div>
  {% endif %}
  <h2 class="border-bottom py-2">{{ question.subject }}</h2>
  <div class="row my-3">
    <div class="col-1"> <!-- 추천 영역 -->
      <div class="bg-light text-center p-3 border font-weight-bolder mb-1">
           {{ question.voter.count }}
      </div>
      <a href="#" data-uri="{% url 'pybo:vote_question' question.id %}"
         class="recommend btn btn-sm btn-secondary btn-block my-1">추천</a>
    </div>
    <div class="col-11">
      <div class="card my-3">
        <div class="card-body">
          <div class="card-text" style="white-space: pre-line;">
          <!--텍스트의 줄바꿈을 정상적으로 보이게함-->
            {{ question.content }}
          </div>
          <div class="d-flex justify-content-end">
            {% if question.modify_date %}
            <div class="badge badge-light p-2 text-left mx-3">
              <div class="mb-2">modified at</div>
              <div>{{ question.modify_date }}</div>
            </div>
            {% endif %}
            <div class="badge badge-light p-2 text-left">
              <div class="mb-2">{{ question.author.username }}</div>
              <div>{{ question.create_date }}</div>
            </div>
          </div>
          {% if request.user == question.author %}
          <div class="my-3">
            <a href="{% url 'pybo:question_modify' question.id %}"
               class="btn btn-sm btn-outline-secondary">수정</a>
            <a href="#" class="delete btn btn-sm btn-outline-secondary"
               data-uri="{% url 'pybo:question_delete' question.id %}">삭제</a>
          </div>
          {% endif %}
        <!--질문 댓글 Start-->
          {% if question.comment_set.count > 0 %}
          <div class="mt-3">
            {% for comment in question.comment_set.all %}
            <div class="comment py-2 text-muted">
              <span style="white-space: pre-line;">
                {{ comment.content }}
              </span>
              <span>
                - {{ comment.author }}, {{ comment.create_date }}
                {% if comment.modify_date %}
                  (수정:{{ comment.modify_date }})
                {% endif %}
              </span>
              {% if request.user == comment.author %}
              <a href="{% url 'pybo:comment_modify_question' comment.id %}" class="small">수정</a>
              <a href="#" class="small delete"
                 data-uri="{% url 'pybo:comment_delete_question' comment.id %}">삭제</a>
              {% endif %}
            </div>
            {% endfor %}
          </div>
          {% endif %}
          <div>
            <a href="{% url 'pybo:comment_create_question' question.id %}" class="small">
              <small>댓글 추가 ..</small>
            </a>
          </div>
        <!-- 질문 댓글 End-->
        </div>
      </div>
    </div>
  </div>
  <h5 class="border-bottom my-3 py-2">
    {{ question.answer_set.count }}개의 답변이 있습니다.
  </h5>
  {% for answer in question.answer_set.all %}
  <div class="row my-3">
    <div class="col-1"> <!-- 답변 추천 영역-->
      <div class="bg-light text-center p-3 border font-weight-bolder mb-1">
           {{ answer.voter.count }}
      </div>
      <a href="#" data-uri="{% url 'pybo:vote_answer' answer.id %}"
         class="recommend btn btn-sm btn-secondary btn-block my-1">추천</a>
    </div>
    <div class="col-11">
      <div class="card my-3">
        <div class="card-body">
          <div class="card-text" style="white-space: pre-line;">
          <!--텍스트의 줄바꿈을 정상적으로 보이게함-->
            {{ answer.content }}
          </div>
          <div class="d-flex justify-content-end">
            {% if answer.modify_date %}
            <div class="badge badge-light p-2 text-left mx-3">
              <div class="mb-2">modified at</div>
              <div>{{ answer.modify_date }}</div>
            </div>
            {% endif %}
            <div class="badge badge-light p-2 text-left">
              <div class="mb-2">{{ answer.author.username }}</div>
              <div>{{ answer.create_date }}</div>
            </div>
          </div>
          {% if request.user == answer.author %}
          <div class="my-3">
            <a href="{% url 'pybo:answer_modify' answer.id %}"
               class="btn btn-sm btn-outline-secondary">수정</a>
            <a href="#" data-uri="{% url 'pybo:answer_delete' answer.id %}"
               class="delete btn btn-sm btn-outline-secondary">삭제</a>
          </div>
          {% endif %}
          <!--답변 댓글 Start-->
          {% if answer.comment_set.count > 0 %}
          <div class="mt-3">
            {% for comment in answer.comment_set.all %}
            <div class="comment py-2 text-muted">
              <span style="white-space: pre-line;">
                {{ comment.content }}
              </span>
              <span>
                - {{ comment.author }}, {{ comment.create_date }}
                {% if comment.modify_date %}
                  (수정:{{ comment.modify_date }})
                {% endif %}
              </span>
              {% if request.user == comment.author %}
                <a href="{% url 'pybo:comment_modify_answer' comment.id %}" class="small">수정</a>
                <a href="#" class="small delete"
                   data-uri="{% url 'pybo:comment_delete_answer' comment.id %}">삭제</a>
              {% endif %}
            </div>
            {% endfor %}
          </div>
          {% endif %}
          <div>
            <a href="{% url 'pybo:comment_create_answer' answer.id %}" class="small">
              <small>댓글 추가 ..</small>
            </a>
          </div>
          <!-- 답변 댓글 End-->
        </div>
      </div>
    </div>
  </div>
  {% endfor %}
  <!--답변 등록 폼-->
  <form action="{% url 'pybo:answer_create' question.id %}" method="post">
    {% csrf_token %}
    <!-- 유효성 위배 오류 처리 시작-->
    {% if form.errors %}
    <div class="alert alert-danger" role="alert">
      {% for field in form %}
        {% if field.errors %}
        <strong>{{ field.label }}</strong>
           {{ field.errors }}
        {% endif %}
      {% endfor %}
    </div>
    {% endif %}
    <!-- 유효성 위배 오류 처리 끝-->
    <div class="form-group">
      <textarea name="content" id="content"
                rows="10" class="form-control"
                {% if not user.is_authenticated %}
                    disabled
                {% endif %}></textarea>
    </div>
    <input type="submit" value="답변 등록" class="btn btn-primary">
  </form>
</div>
{% endblock %}
{% block script %}
<script>
  $(function(){
    // 삭제 확인
    $(".delete").on("click", function(){
      if(confirm("정말로 삭제하시겠습니까?")){
         location.href = $(this).data('uri');
       }
    });

    //추천 확인
    $(".recommend").on('click', function(){
      if(confirm("정말로 추천하시겠습니까?")){
        location.href = $(this).data('uri')
      }
    });
  });
</script>
{% endblock %}

templates/pybo/question_list.html
{% extends 'base.html' %}  <!--템플릿 상속-->
{% load pybo_filter %}
{% block content %}
<div class="container my-3">
    <div class="row justify-content-between my-3">
        <!--정렬(sort) 선택-->
        <div class="col-2">
           <select class="form-control so">
               <option value="recent" {% if so == 'recent' %}selected{% endif %}>
                   최신순
               </option>
               <option value="recommend" {% if so == 'recommend' %}selected{% endif %}>
                   추천순
               </option>
               <option value="popular" {% if so == 'popular' %}selected{% endif %}>
                   인기순
               </option>
           </select>
        </div>
        <!--검색 창-->
        <div class="col-4 input-group">
            <input type="text" class="form-control kw"
                   value="{{ kw|default_if_none:'' }}">
            <div class="input-group-append">
                <button class="btn btn-outline-secondary"
                        type="button" id="btn_search">찾기</button>
            </div>
        </div>
    </div>
    <form id="searchForm" method="get" action="{% url 'pybo:board' %}">
        <input type="hidden" name="kw" id="kw" value="{{ kw|default_if_none:'' }}">
        <input type="hidden" name="page" id="page" value="{{ page }}">
        <input type="hidden" name="so" id="so" value="{{ so }}">
    </form>
    <table class="table">
        <thead>
            <tr class="thead-dark text-center">
                <th>번호</th>
                <th style="width:50%">제목</th>
                <th>글쓴이</th>
                <th>작성일자</th>
            </tr>
        </thead>
        <tbody>
        {% if question_list %}
            {% for question in question_list %}
            <tr class="text-center">
                <!--<td>{{ forloop.counter }}</td>    번호가 페이징 처리 안됨-->
                <td>{{ question_list.paginator.count|sub:question_list.start_index|sub:forloop.counter0|add:1 }}</td>
                <td class="text-left">
                    <a href="{% url 'pybo:detail' question.id %}">
                        {{ question.subject }}
                        {% if question.answer_set.count %}
                        <span class="text-danger small ml-2">
                            {{ question.answer_set.count }}
                        </span>
                        {% endif %}
                    </a>
                </td>
                <td>{{ question.author.username }}</td>
                <td>{{ question.create_date }}</td>
            </tr>
            {% endfor %}
        {% else %}
            <tr>
                <td colspan="3">질문이 없습니다.</td>
            </tr>
        {% endif %}
        </tbody>
    </table>
    <!--페이징 처리 시작-->
    <ul class="pagination justify-content-center">
    <!--이전 페이지-->
        {% if question_list.has_previous %}
        <div class="page-item">
            <a class="page-link" href="#"
               data-page="{{ question_list.previous_page_number }}">
                이전
            </a>
        </div>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">
                이전
            </a>
        </li>
        {% endif %}
    <!--페이지 리스트-->
        {% for page_number in question_list.paginator.page_range %}
            {% if page_number == question_list.number%}
            <li class="page-item active" aria-current="page">
                <a class="page-link" href="#"
                   data-page="{{ page_number }}">
                    {{ page_number }}
                </a>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" href="#"
                   data-page="{{ page_number }}">
                    {{ page_number }}
                </a>
            </li>
            {% endif %}
        {% endfor %}
        <!--다음 페이지-->
        {% if question_list.has_next %}
        <div class="page-item">
            <a class="page-link" href="#"
               data-page="{{ question_list.next_page_number }}">
                다음
            </a>
        </div>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">
                다음
            </a>
        </li>
        {% endif %}
    <!--페이징 처리 끝-->
    </ul>
    <a href="{% url 'pybo:question_create' %}" class="btn btn-primary">
        질문 등록하기
    </a>
</div>
{% endblock %}
{% block script %}
<script>
    $(document).ready(function(){
        // 페이지 처리 -> 찾기 폼에서 전송
        $(".page-link").on('click', function(){
            $("#page").val($(this).data("page"));
            $("#searchForm").submit();
        })

        // 검색 처리(찾기)
        $("#btn_search").on('click', function(){
            $("#kw").val($(".kw").val());
            $("#page").val(1);    //1페이지부터 조회
            $("#searchForm").submit();
        });

        //정렬 처리
        $(".so").on('change', function(){ //change -> select(선택) : 변경 이벤트
            $("#so").val($(this).val());
            $("#page").val(1);
            $("#searchForm").submit();
        });
    });

</script>
{% endblock %}