common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(
        template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]
# 제네릭 뷰 방식 - 함수를 직접 정의할 필요가 없음

config/urls.py
from django.contrib import admin
from django.urls import path, include
from pybo.views import base_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('common/', include('common.urls')),
    path('', base_views.index, name='index')
]

pybo/urls.py
from django.urls import path

from .views import base_views, question_views, answer_views, vote_views, comment_views

app_name = 'pybo'
# url 별칭 -> 네임 스페이스

urlpatterns = [
    # base_views.py
    # 인덱스 메인
    path('', base_views.index, name='index'),
    # 질문/답변 게시판
    path('board/', base_views.board, name='board'),
    # 나의 프로필
    path('profile/', base_views.profile, name='profile'),
    # 상세 페이지
    path('<int:question_id>/', base_views.detail, name='detail'),

    # question_views.py
    # 질문 등록
    path('question/create/', question_views.question_create,
         name='question_create'),
    # 질문 수정
    path('question/modify/<int:question_id>/', question_views.question_modify,
         name='question_modify'),
    # 질문 삭제
    path('question/delete/<int:question_id>/', question_views.question_delete,
         name='question_delete'),

    # answer_views.py
    # 답변 등록
    path('answer/create/<int:question_id>/', answer_views.answer_create,
         name='answer_create'),
    # 답변 수정
    path('answer/modify/<int:answer_id>/', answer_views.answer_modify,
         name='answer_modify'),
    # 답변 삭제
    path('answer/delete/<int:answer_id>/', answer_views.answer_delete,
         name='answer_delete'),

    # vote_views.py
    # 질문 추천
    path('vote/question/<int:question_id>/', vote_views.vote_question,
         name='vote_question'),
    # 답변 추천
    path('vote/answer/<int:answer_id>', vote_views.vote_answer,
         name='vote_answer'),

    # comment_views.py
    # 질문 댓글 등록
    path('comment/create/question/<int:question_id>', comment_views.comment_create_question,
         name='comment_create_question'),
    # 질문 댓글 수정
    path('comment/modify/question/<int:comment_id>', comment_views.comment_modify_question,
         name='comment_modify_question'),
    # 질문 댓글 삭제
    path('comment/delete/question/<int:comment_id>', comment_views.comment_delete_question,
         name='comment_delete_question'),
    # 답변 댓글 등록
    path('comment/create/answer/<int:answer_id>/', comment_views.comment_create_answer,
         name='comment_create_answer'),
    # 답변 댓글 수정
    path('comment/modify/answer/<int:comment_id>/', comment_views.comment_modify_answer,
         name='comment_modify_answer'),
    # 답변 댓글 삭제
    path('comment/delete/answer/<int:comment_id>/', comment_views.comment_delete_answer,
         name='comment_delete_answer'),

]

common/models.py
from django.db import models

# Create your models here.

common/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

class UserForm(UserCreationForm):
    email = forms.EmailField(label="이메일")

    class Meta:
        model = User
        fields =('username', 'email')

common/views.py
from django.shortcuts import render, redirect
from .forms import UserForm
from django.contrib.auth import authenticate, login

def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            password1 = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password1) #로그인
            login(request, user)   # 세션 권한을 획득(인증)
            return redirect('index')
    else:  # GET
        form = UserForm()
    context = {'form': form}
    return render(request, 'common/signup.html', context)

templates/common/login.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
  <div class="row">
    <div class="col-4">
      <h4>로그인</h4>
    </div>
    <div class="col-8 text-right">
      <span>또는 <a href="{% url 'common:signup' %}">계정을 만드세요</a></span>
    </div>
  </div>
  <form action="{% url 'common:login' %}" method="post" class="post-form">
    {% csrf_token %}
    {% include 'form_errors.html' %}
    <div class="form-group">
      <label for="username">사용자ID</label>
      <input type="text" class="form-control" name="username" id="username"
             value="{{ form.username.value|default_if_none:'' }}">
    </div>
    <div class="form-group">
      <label for="password">비밀번호</label>
      <input type="password" class="form-control" name="password" id="password"
             value="{{ form.password.value|default_if_none:'' }}">
    </div>
    <button type="submit" class="btn btn-primary">로그인</button>
  </form>
 </div>
{% endblock %}

templates/common/signup.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <div class="row my-3">
        <div class="col-4">
            <h4>회원가입</h4>
        </div>
        <div class="col-8 text-right">
            <span>또는 <a href="{% url 'common:login' %}">로그인하세요</a></span>
        </div>
    </div>
    <form method="post" class="post-form">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="username">사용자 이름</label>
            <input type="text" name="username" id="username" class="form-control"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password1">비밀번호</label>
            <input type="password" name="password1" id="password1" class="form-control"
                   value="{{ form.password1.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password2">비밀번호 확인</label>
            <input type="password" name="password2" id="password2" class="form-control"
                   value="{{ form.password2.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="email">이메일</label>
            <input type="text" name="email" id="email" class="form-control"
                   value="{{ form.email.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">생성하기</button>
    </form>
</div>
{% endblock %}