common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(
        template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]
# 제네릭 뷰 방식 - 함수를 직접 정의할 필요가 없음

config/urls.py
from django.contrib import admin
from django.urls import path, include
from pybo.views import base_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('common/', include('common.urls')),
    path('', base_views.index, name='index')
]

pybo/urls.py
from django.urls import path

from .views import base_views, question_views, answer_views, vote_views, comment_views

app_name = 'pybo'
# url 별칭 -> 네임 스페이스

urlpatterns = [
    # base_views.py
    # 인덱스 메인
    path('', base_views.index, name='index'),
    # 질문/답변 게시판
    path('board/', base_views.board, name='board'),
    # 나의 프로필
    path('profile/', base_views.profile, name='profile'),
    # 상세 페이지
    path('<int:question_id>/', base_views.detail, name='detail'),

    # question_views.py
    # 질문 등록
    path('question/create/', question_views.question_create,
         name='question_create'),
    # 질문 수정
    path('question/modify/<int:question_id>/', question_views.question_modify,
         name='question_modify'),
    # 질문 삭제
    path('question/delete/<int:question_id>/', question_views.question_delete,
         name='question_delete'),

    # answer_views.py
    # 답변 등록
    path('answer/create/<int:question_id>/', answer_views.answer_create,
         name='answer_create'),
    # 답변 수정
    path('answer/modify/<int:answer_id>/', answer_views.answer_modify,
         name='answer_modify'),
    # 답변 삭제
    path('answer/delete/<int:answer_id>/', answer_views.answer_delete,
         name='answer_delete'),

    # vote_views.py
    # 질문 추천
    path('vote/question/<int:question_id>/', vote_views.vote_question,
         name='vote_question'),
    # 답변 추천
    path('vote/answer/<int:answer_id>', vote_views.vote_answer,
         name='vote_answer'),

    # comment_views.py
    # 질문 댓글 등록
    path('comment/create/question/<int:question_id>', comment_views.comment_create_question,
         name='comment_create_question'),
    # 질문 댓글 수정
    path('comment/modify/question/<int:comment_id>', comment_views.comment_modify_question,
         name='comment_modify_question'),
    # 질문 댓글 삭제
    path('comment/delete/question/<int:comment_id>', comment_views.comment_delete_question,
         name='comment_delete_question'),
    # 답변 댓글 등록
    path('comment/create/answer/<int:answer_id>/', comment_views.comment_create_answer,
         name='comment_create_answer'),
    # 답변 댓글 수정
    path('comment/modify/answer/<int:comment_id>/', comment_views.comment_modify_answer,
         name='comment_modify_answer'),
    # 답변 댓글 삭제
    path('comment/delete/answer/<int:comment_id>/', comment_views.comment_delete_answer,
         name='comment_delete_answer'),

]

pybo/views/base_views.py
from django.core.paginator import Paginator
from django.db.models import Count, Q
from django.shortcuts import render, get_object_or_404

from pybo.models import Question


def index(request):
    return render(request, 'pybo/index.html')

def profile(request):
    return render(request, 'pybo/profile.html')

def board(request):
    # 질문 목록
    # 127.0.0.1:8000/pybo/board/?page=1
    page = request.GET.get('page', '1')  # 페이지
    kw = request.GET.get('kw', '')       # 검색어
    so = request.GET.get('so', 'recent') # 정렬 기준

    # 정렬
    if so == 'recommend':
        question_list = Question.objects.annotate( #num_voter : 임시 필드
            num_voter=Count('voter')).order_by('-num_voter', '-create_date')
    elif so == 'popular':
        question_list = Question.objects.annotate( #num_answer : 임시 필드
            num_answer=Count('answer')).order_by('-num_answer', '-create_date')
    else:  # recent
        question_list = Question.objects.order_by('-create_date')

    if kw:
        question_list = question_list.filter(
            Q(subject__icontains=kw) |           # 제목 검색
            Q(content__icontains=kw) |           # 내용 검색
            Q(author__username__icontains=kw) |  # 질문 글쓴이
            Q(answer__author__username__icontains=kw) |#답변 글쓴이
            Q(answer__content__icontains=kw)
        ).distinct()    # 중복제거

    # 페이징 처리 -페이지당 10개씩 보여줌
    paginator = Paginator(question_list, 10)
    page_obj = paginator.get_page(page)

    context = {'question_list': page_obj, 'page': page, 'kw': kw, 'so':so}
    return render(request, 'pybo/question_list.html' ,context)

def detail(request, question_id):
    #question = Question.objects.get(id=question_id)
    question = get_object_or_404(Question, pk=question_id)
    context ={'question' : question}
    return render(request, 'pybo/question_detail.html', context)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'pybo/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'pybo/style.css' %}">
    <title>Hello~ Pybo</title>
</head>
<body>
{% include 'navbar.html' %}
<!--기본 템플릿 안에 삽입될 내용 start-->
{% block content %}

{% endblock %}
<!--기본 템플릿 안에 삽입될 내용 end-->
<script src="{% static 'pybo/jquery-3.6.0.js' %}"></script>
<script src="{% static 'pybo/bootstrap.js' %}"></script>
<!--자바스크립트 Statr-->
{% block script %}
{% endblock %}
<!--자바스크립트 End-->
</body>
</html>

templates/form_errors.html
{% if form.errors %}  <!--필드 오류 출력 -->
    {% for field in form %}
      {% for error in field.errors %}
        <div class="alert alert-danger">
          <strong>{{ field.label }}</strong>
          {{error}}   <!-- 필수 항목입니다.-->
        </div>
      {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %} <!-- 넌필드 오류-->
        <div class="alert alert-danger">
            <strong>{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}

templates/navbar.html
<!--네비게이션 바-->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <!-- 로고 부분-->
    <a class="navbar-brand" href="{% url 'pybo:index' %}">PyWeb</a>
    <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse"
            data-target="#navbarNav" aria-controls="navbarNav"
            aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <!--로그인, 로그아웃 부분-->
    <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item">
                {% if user.is_authenticated %}
                    <a class="nav-link" href="{% url 'common:logout' %}">
                        {{ user.username }}(로그아웃)
                    </a>
                {% else %}
                    <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
                {% endif %}
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'pybo:board' %}">질문/답변</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'pybo:profile' %}">나의 프로필</a>
            </li>
        </ul>
    </div>
</nav>